/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CardsParams": {
      "DOMAIN_NAME": string
      "STREAMER_USER_ID": string
      "TWITCH_TOKENS_PARAM": string
      "type": "sst.sst.Linkable"
    }
    "DataSummaries": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TWITCH_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWITCH_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebsocketApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "WebsocketApiConnectionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "data": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}