name: Deploy QA

on:
    push:
        branches:
            - qa

jobs:
    deploy-qa:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 8.14.0

            - name: Install dependencies
              run: pnpm install

            - name: Deploy SST app
              run: pnpm run deploy --stage "${GITHUB_REF##*/}"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
